version: 2.1
jobs: 
  test: 
    docker:       
      - image: cimg/base:stable        
    steps:       
      - run: 
          command: |
            if [ -n ${CIRCLE_PR_NUMBER:-} ]; then
              local base_branch=$(curl -fsSL https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls/$CIRCLE_PR_NUMBER | jq -r '.base.ref')
            else
              local base_branch=$CIRCLE_BRANCH
            fi         
workflows:
  branch-test:
    jobs:
      - test
